name: Build the app and execute integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_execute_integration_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Dotnet build
      run: dotnet build --no-restore
    - name: Execute integration tests
      run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration.csproj --no-build --verbosity normal
