name: .NET

on:
  push:
    branches: [ "develop" ]

jobs:
  build_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test Horizons.Test.Unit/Horizons.Test.Unit.csproj --no-build --verbosity normal
