name: Build and run Integration Tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET v8.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Build
      run: dotnet build --no-restore
    - name: Run Integration Test
      run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration --no-build --verbosity normal
