# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Run Unit Tests

on:
  push:
    branches: [ "develop" ]

jobs:
  build_run_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo on the Ubuntu runner
      uses: actions/checkout@v4
    - name: Setup .NET on the Ubuntu runner
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Unit Tests
      run: dotnet test Horizons.Tests.Unit/Horizons.Tests.Unit.csproj --no-build --verbosity normal
