name: Build and run unit tests on develop branch

on:
  push:
    branches: [ "develop" ]

jobs:
  build_run_unit_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run unit tests
      run: dotnet test Horizons.Tests.Unit --no-build --verbosity normal
