# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - develop
      - feature/**

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust as needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet vstest Horizons.Tests.Unit/Horizons.Tests.Unit.csproj

      - name: Run integration tests
        run: dotnet vstest Horizons.Tests.Integration/Horizons.Tests.Integration.csproj

          