name: CI

on:
  push:
    branches:
      - develop
      - 'feature'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore Horizons.sln

      - name: Build
        run: dotnet build Horizons.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Horizons.sln --no-build --verbosity normal
