

name: Build and Test unit tests 

on:
  push:
    branches: [ "develop" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build unit tests 
      run: dotnet build --no-restore
    - name: Test unit tests 
      run: dotnet test Horizons.Tests.Unit/Horizons.Tests.Unit.csproj --verbosity normal
