name: Build and run integration tests

on:
  push:
    branches: [ "staging" ]

jobs:
  build_run_integration_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup .NET version 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore project dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build --no-restore
    - name: Run integration tests
      run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration.csproj --no-build --verbosity normal
