name: Build and Integration Tests (Staging)

on:
  push:
    branches:
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Run integration tests
        run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration.csproj --configuration Release --no-build
