

name: Running Integration Tests on STAGE

on:
  push:
    branches: [ "staging" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout 
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Application
      run: dotnet build --no-restore
    - name: Run Integration Test on STAGE
      run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration.csproj --no-build --verbosity normal
